### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by TeamStriebigSebastian** [shobrook/adrenaline#15]
Tried to create login
on 
https://useadrenaline.com/playground
and 
locally.
Both times it tells me 
Failed to create account

**Comment by thiago-scherrer** [comment]
Same here!
btw It's not asking for the API key anymore even locally:
![image](https://user-images.githubusercontent.com/46422437/212912107-5686ec2b-5d74-4371-a79f-5decf5baf524.png)

**Comment by SpaceOddityTr** [comment]
same problem, i have tried different emails and passwords and nothing works

**Comment by thiago-scherrer** [comment]
Fixed => https://github.com/shobrook/adrenaline/pull/14
