### ISSUE TITLE
[BUG] Adrenaline is asking for API key even if it's already provided

### ISSUE THREAD

**Issue by Andrej730** [shobrook/adrenaline#17]
![image](https://user-images.githubusercontent.com/9417531/213671297-44b415ba-9bf9-4692-9764-645a99859b92.png)

I've typed in the code and the error message and after I try to use "Debug" it's asking me for API key. 
After I click "Done" there is no error message or anything but if use "Debug" it's still asking for API key.

**Comment by vasilekx** [comment]
I've the same problem.

**Comment by shobrook** [comment]
Should be fixed now that API requests are handled in the backend.

**Comment by Andrej730** [comment]
@shobrook is it using your backend's Open AI keys? Now can't find an option to enter my key.
