### ISSUE TITLE
 suggest using https://github.com/microsoft/monaco-editor as code editor

### ISSUE THREAD

**Issue by AwesomeYuer** [shobrook/adrenaline#2]
demo:
https://microsoft.github.io/monaco-editor/
you can get vscode's programing/editing experience, such as:
Rich IntelliSense, Validation
TypeScript, JavaScript, CSS, LESS, SCSS, JSON, HTML

Basic Syntax Colorization
XML, PHP, C#, C++, Razor, Markdown, Diff, Java, VB, CoffeeScript, Handlebars, Batch, Pug, F#, Lua, Powershell, Python, Ruby, SASS, R, Objective-C

code editing action
CTRL+A: select all
ALT + SHIFT + F: format
CTRL + F: find
etc.

**Comment by shobrook** [comment]
If you can get the diff UI to work with Monaco, please be my guest.

**Comment by AwesomeYuer** [comment]
https://github.com/AwesomeYuer/JsonStructuresDiffAssistantToolsOnline/blob/aa636257e95f7b137da773f154cc19d223568dc2/index.html#L821
