### ISSUE TITLE
API Endpoint

### ISSUE THREAD

**Issue by saliksik** [shobrook/adrenaline#20]
Hi Sir!

Do you have plans open sourcing the API endpoint of Adrenaline? https://rubrick-api-production.up.railway.app/api/

Thank you.

**Comment by jontstaz** [comment]
+1
This would be very much appreciated if you open-sourced the backend. Is there any reason why it wasn't released together with the frontend originally @shobrook ?

**Comment by jontstaz** [comment]
Additionally, these constants do nothing as it stands. Everything happens on the backend:
```javascript
const EDIT_PROMPT_PARAMS = {
  model: "code-davinci-edit-001"
};
const COMPLETION_PROMPT_PARAMS = {
  model: "text-davinci-003",
  max_tokens: 500,
  temperature: 0.2,
  top_p: 1,
  presence_penalty: 0,
  frequency_penalty: 0,
  best_of: 1,
  n: 1,
  stream: false
};
```

**Comment by jamesphillipturpin** [comment]
I haven't read the source code in its entirety, but just looking at your comments, "code-davinci-edit-001" and "text-davinci-003" appear to be OpenAI models that are known to only be available through Open AI's API.

It might be possible to refactor the code to use other models that are downloadable, but the downloadable models may not be as good in terms of high level comprehension. You can actually get help from ChatGPT with setting up the downloadable models such as GPT 2. It is over 10 GB though. Once you get a code model and an natural language model setup, you can go to the facehugger community webpage and explore options to possible switch out with other models.

**Comment by osanseviero** [comment]
With the release of cool open source models such as Code Llama, I was wondering if this changed

**Comment by shobrook** [comment]
Right now the API is closed-source but we will explore exposing some endpoints in the future (specifically for generating visualizations). 

And yeah nothing beats GPT-4 right now.
