### ISSUE TITLE
Feature: Adrenaline CLI 

### ISSUE THREAD

**Issue by sam5epi0l** [shobrook/adrenaline#21]
AI debugger takes multiple debug-run-debug steps.

So, it would be great if we can use a command line interface which can read single/multiple code files. The program can be run as usual and STDERR is piped to the adrenaline. Then, it can modify the code with/without manual interaction. 

This can looped until there is not error when we run the program.

```bash
cargo run | adrenaline-cli --code src/main.rs --api-token XXXX
```

**Comment by daefv** [comment]
Indeed. Perhaps the AI could ask user for user input to make specific modifications along the way - making sure you don't end up with a working code that took 1 hour to produce, but is not precisely what you wanted.

**Comment by FarisHijazi** [comment]
I personally am interested in a CLI version of this, do you guys know of any similar projects?

**Comment by daefv** [comment]
Chat GPt does CLI

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FarisHijazi** [comment]
@sam5epi0l did you find something similar to this?

**Comment by sam5epi0l** [comment]
Nope, I wonder if something like AutoGPT could do it. never tried it though.

**Comment by shobrook** [comment]
Hey all, looks like this exists already:

https://github.com/biobootloader/wolverine
