### ISSUE TITLE
When the server is full, you can trigger a response twice

### ISSUE THREAD

**Issue by daefv** [shobrook/adrenaline#25]
<img width="1440" alt="Screen Shot 2023-03-11 at 6 26 15 PM" src="https://user-images.githubusercontent.com/127538197/224516011-d432a920-1460-4765-83ca-f3546a09708f.png">

**Comment by waqaspathan00** [comment]
Triggering a response twice doesnt guarantee an output

**Comment by daefv** [comment]
indeed. in fact it guarantees 0 output. it is a bug.

**Comment by waqaspathan00** [comment]
I misunderstood, good catch

**Comment by shobrook** [comment]
Closed as this is related to an old version of the site.
