### ISSUE TITLE
Example inputs

### ISSUE THREAD

**Issue by waqaspathan00** [shobrook/adrenaline#27]
As a user, I would like to be able to run some sample inputs to see how the program works. Similar to how ChatGPT has some sample inputs like "Explain quantum computing...", we can preload the code input and the prompt input with some sample data.

### ChatGPT Initial Interface Reference

<img width="900" alt="Screenshot 2023-03-12 at 3 39 52 PM" src="https://user-images.githubusercontent.com/67988358/224568897-92f94247-8276-4e9e-86b4-7a74f9a17801.png">

**Comment by daefv** [comment]
if you pay for the use of Adrenaline you can run the code in Adrenaline. Also the first output of Adrenaline is always an explanation of the pasted code. 'Quantum computing' is not a code, so an explanation of it should not come from Adrenaline.

**Comment by waqaspathan00** [comment]
When I said sample inputs it would be code related, not general QA. Heres an example:

Sample prompt: `modify this function so that it left pads the variables with 0 if they are less than 10 and returns the result`

Sample Code: 
```javascript
export function getFormattedTime2(time: number) {
    const minutes = time / 60;
    const seconds = time % 60;

    return `${minutes}:${seconds}`;
}
```

**Comment by shobrook** [comment]
Closed as this is now an issues-only repository.
