### ISSUE TITLE
how to change default language and clear demo code

### ISSUE THREAD

**Issue by yuexiadudiao** [shobrook/adrenaline#3]
i deploy this project for myself, and mostly write c++ code, how to set c++ as default language and don't show demo code on editor

i try to modify App.js ,but it doesnt work as what i want

**Comment by shobrook** [comment]
Thanks for pointing this out. Right now the default language is Python, but I can open a PR to cache the language you select and the code in the editor.

**Comment by Mbladra** [comment]
@waqaspathan00 made a fix for caching the language with #24
