### ISSUE TITLE
Eternal error "Code execution is not available at this time due to a heavy volume of requests.", even with a paid subscription. Subscription is not refunded.

### ISSUE THREAD

**Issue by vplenu** [shobrook/adrenaline#32]
Initially there was no such problem. A couple of weeks ago I decided to use Adrenaline, but at any time, on any day I get the error: "Code execution is not available at this time due to a heavy volume of requests.
After paying the subscription - the error did not go anywhere. I decided to wait a bit and try again. The error kept appearing. I wanted to go back to the free subscription to double-check, but after choosing a free subscription - paid subscription was canceled and the site offered to pay again. Sales department did not answer anything after a week of asking. The result: the site always gives this error, the subscription is not returned, the same money is not returned.

**Comment by Raghav-Verma21** [comment]
This is an outstanding idea-so load is expected.
 How can we overcome this issue? 
 - By level up the database memory enhancement.
 
 **I am a beginner wants to contribute in this project** to solve issues

**Comment by vplenu** [comment]
> This is an outstanding idea-so load is expected. How can we overcome this issue?
> 
> * By level up the database memory enhancement.
> 
> **I am a beginner wants to contribute in this project** to solve issues

How does this help me?
The fact that you don't have enough power is not my problem. Either fix the problems or get your money back.
