### ISSUE TITLE
Feature request: Remove the repositories and code snippet

### ISSUE THREAD

**Issue by fanfan1609** [shobrook/adrenaline#41]
Hi,

I have recently tried and feel so excited about Adrenaline. 
How about removing or deleting the imported Github repositories and code snippets?

**Comment by ouabout** [comment]
Have you gotten the repo to run locally? I tried it, but keep getting NEXT_PUBLIC_WEBSOCKET_URI undefined error when trying to add github repo. Any suggestions on how to fix it? Thanks!

**Comment by fanfan1609** [comment]
@ouabout 
I used it on the cloud and it worked perfectly. 
Let me try on my locally.

**Comment by shobrook** [comment]
Done!
