### ISSUE TITLE
Update needed to the Install and run instructions 

### ISSUE THREAD

**Issue by ProgramItUp** [shobrook/adrenaline#47]
I'd like to try Adrenaline but the instructions on [https://github.com/shobrook/adrenaline](https://github.com/shobrook/adrenaline) need to be updated.

```
$ npm install
$ npm run start-local
```

Throws the error: 
```
~/code/adrenaline$ npm run start-local
npm ERR! Missing script: "start-local"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
~/code/adrenaline$ npm run
Lifecycle scripts included in adrenaline@0.1.0:
  start
    next start

available via `npm run-script`:
  dev
    next dev
  build
    next build
'''

**Comment by Klaudioz** [comment]
Also, there is no mention of how to add the env variables or use a .env file.

**Comment by Znoy108x** [comment]
> npm run start-local

Did you figured out how to add env variables??

**Comment by shobrook** [comment]
Closed as this is now an issues-only repository.
