### ISSUE TITLE
Getting NEXT_PUBLIC_WEBSOCKET_URI undefined error

### ISSUE THREAD

**Issue by ouabout** [shobrook/adrenaline#48]
I get this error when trying to add code snippet or github repo. Any suggestion on how to fix this?

**Comment by fanfan1609** [comment]
it seems you need to set the public websocket uri for the environment variable.

**Comment by FarisHijazi** [comment]
any news on this? is there a backend server we have to be running?

**Comment by shobrook** [comment]
Closing as we've now converted this into an issues-only repository.

**Comment by gshpychka** [comment]
> Closing as we've now converted this into an issues-only repository.

but it's an issue?
