### ISSUE TITLE
Missing font - Helvetica Neue

### ISSUE THREAD

**Issue by Ademking** [shobrook/adrenaline#5]
First of all, keep up the good work! 👍 

I am currently using Windows 11 and noticed that the font on the website appears to be missing. 

I believe the missing font is "Helvetica Neue." This font is not installed by default on Windows systems, and as a result, the website's text is not displaying correctly.

![image](https://user-images.githubusercontent.com/12462188/212502019-a6cc1c27-96b8-4ac4-a749-7399ebe27c62.png)

I recommend that you include "Helvetica Neue" as a web font, possibly through a service like Google Fonts. This will ensure that the text displays correctly for all users, regardless of their operating system.

![](https://i.imgur.com/IqMLalk.png)

![](https://i.imgur.com/WU4YtSv.png)

**Comment by briannarenni** [comment]
Windows famously doesn't play well with Helvetica Neue because of the rendering differences between the two OS. I haven't looked over the code yet but if that's in the fallback stack, it can easily be replaced with Arial. I can take a  quick look now though.

**Comment by briannarenni** [comment]
@Ademking Got you fam 😎 Tested it on my PC too.

**Comment by shobrook** [comment]
[Pushed a fix.](https://github.com/shobrook/adrenaline/commit/482e9bd5971994fa26ec34b7b57de632eb131db0) Will deploy soon. Thanks for bringing this up!

**Comment by Ademking** [comment]
Are you sure it's fixed ? I've test it now and it's the same issue. I've cleared the cache and nothing changed

![image](https://user-images.githubusercontent.com/12462188/219000737-d538fead-5301-418d-ab28-86d60e64a0c3.png)

**Comment by briannarenni** [comment]
@Ademking  You're still seeing the faulty rendering because that push still has Helvetica in the font stacks. It would have to be totally replaced by Arial in all font-stack rules, as I did in my PR. Probably won't get to it until the next deploy.
