### ISSUE TITLE
cannot fetch private repos

### ISSUE THREAD

**Issue by Fedy-Sexy-Vibes** [shobrook/adrenaline#51]
<img width="633" alt="Screenshot 2023-04-04 at 10 44 02" src="https://user-images.githubusercontent.com/126262846/229737982-61aa25f5-b9df-4679-be7e-815a9a74e86a.png">

i have only 2 private repos and its just stuck in an infinite loop trying to fetch the repos

**Comment by woutheijnen** [comment]
Can confirm, was looking for the same thing this morning and could find all my public repos but not private ones

**Comment by shobrook** [comment]
Resolved now
