### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by yuexiadudiao** [shobrook/adrenaline#52]
i get a browser error：

Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by ajthinking** [comment]
Same here. It says: `DOMException: Failed to construct 'WebSocket': The URL 'undefinedanswer_query' is invalid.`

**Comment by wtcitmanager** [comment]
Same here

**Comment by Slach** [comment]
same here

**Comment by digitalw00t** [comment]
same error.  Not seeing anything from the dev team.  Anyone know if this project has been silently dropped?

**Comment by scylamb** [comment]
istener indicated an asynchronous response by returning true, but the message channel closed before a response was received
app:1  Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
app:1  Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
app:1  Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
app-14fa66f40f368b62.js:1 
framework-73b8966a3c579ab0.js:9  TypeError: Cannot read properties of undefined (reading 'push')
    at app-14fa66f40f368b62.js:1:28546
    at Array.reduce (<anonymous>)
    at app-14fa66f40f368b62.js:1:28485
    at Array.forEach (<anonymous>)
    at app-14fa66f40f368b62.js:1:28452
    at n.value (app-14fa66f40f368b62.js:1:28603)
    at um (framework-73b8966a3c579ab0.js:9:75831)
    at up (framework-73b8966a3c579ab0.js:9:75629)
    at i (framework-73b8966a3c579ab0.js:9:120456)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
a5 @ framework-73b8966a3c579ab0.js:9
main-9ed2a15cbc4c1d51.js:1  TypeError: Cannot read properties of undefined (reading 'push')
    at app-14fa66f40f368b62.js:1:28546
    at Array.reduce (<anonymous>)
    at app-14fa66f40f368b62.js:1:28485
    at Array.forEach (<anonymous>)
    at app-14fa66f40f368b62.js:1:28452
    at n.value (app-14fa66f40f368b62.js:1:28603)
    at um (framework-73b8966a3c579ab0.js:9:75831)
    at up (framework-73b8966a3c579ab0.js:9:75629)
    at i (framework-73b8966a3c579ab0.js:9:120456)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
en @ main-9ed2a15cbc4c1d51.js:1

**Comment by madruga8** [comment]
how to disable this login stuff...


(index):9     GET https://www.clarity.ms/tag/h3a3jo2ysj net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ (index):9
(anonymous) @ (index):10
framework-73b8966a3c579ab0.js:9 Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
    
    at _app-7ecd27c8c48459ad.js:1:26461
    at new en (_app-7ecd27c8c48459ad.js:1:26664)
    at _app-7ecd27c8c48459ad.js:1:43792
    at Object.aM [as useState] (framework-73b8966a3c579ab0.js:9:63832)
    at n.useState (framework-73b8966a3c579ab0.js:25:6154)
    at ev (_app-7ecd27c8c48459ad.js:1:43773)
    at ab (framework-73b8966a3c579ab0.js:9:60917)
    at i (framework-73b8966a3c579ab0.js:9:119475)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
    at framework-73b8966a3c579ab0.js:9:98981
a5 @ framework-73b8966a3c579ab0.js:9
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9
uY @ framework-73b8966a3c579ab0.js:9
e @ framework-73b8966a3c579ab0.js:9
(anonymous) @ framework-73b8966a3c579ab0.js:9
oI @ framework-73b8966a3c579ab0.js:9
oS @ framework-73b8966a3c579ab0.js:9
x @ framework-73b8966a3c579ab0.js:33
T @ framework-73b8966a3c579ab0.js:33
main-9ed2a15cbc4c1d51.js:1 Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
    
    at _app-7ecd27c8c48459ad.js:1:26461
    at new en (_app-7ecd27c8c48459ad.js:1:26664)
    at _app-7ecd27c8c48459ad.js:1:43792
    at Object.aM [as useState] (framework-73b8966a3c579ab0.js:9:63832)
    at n.useState (framework-73b8966a3c579ab0.js:25:6154)
    at ev (_app-7ecd27c8c48459ad.js:1:43773)
    at ab (framework-73b8966a3c579ab0.js:9:60917)
    at i (framework-73b8966a3c579ab0.js:9:119475)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
    at framework-73b8966a3c579ab0.js:9:98981
en @ main-9ed2a15cbc4c1d51.js:1
fn @ main-9ed2a15cbc4c1d51.js:1
value @ main-9ed2a15cbc4c1d51.js:1
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9
uY @ framework-73b8966a3c579ab0.js:9
e @ framework-73b8966a3c579ab0.js:9
(anonymous) @ framework-73b8966a3c579ab0.js:9
oI @ framework-73b8966a3c579ab0.js:9
oS @ framework-73b8966a3c579ab0.js:9
x @ framework-73b8966a3c579ab0.js:33
T @ framework-73b8966a3c579ab0.js:33
main-9ed2a15cbc4c1d51.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
en @ main-9ed2a15cbc4c1d51.js:1
fn @ main-9ed2a15cbc4c1d51.js:1
value @ main-9ed2a15cbc4c1d51.js:1
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9
uY @ framework-73b8966a3c579ab0.js:9
e @ framework-73b8966a3c579ab0.js:9
(anonymous) @ framework-73b8966a3c579ab0.js:9
oI @ framework-73b8966a3c579ab0.js:9
oS @ framework-73b8966a3c579ab0.js:9
x @ framework-73b8966a3c579ab0.js:33
T @ framework-73b8966a3c579ab0.js:33
framework-73b8966a3c579ab0.js:9 Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
    
    at _app-7ecd27c8c48459ad.js:1:26461
    at new en (_app-7ecd27c8c48459ad.js:1:26664)
    at _app-7ecd27c8c48459ad.js:1:43792
    at Object.aM [as useState] (framework-73b8966a3c579ab0.js:9:63832)
    at n.useState (framework-73b8966a3c579ab0.js:25:6154)
    at ev (_app-7ecd27c8c48459ad.js:1:43773)
    at ab (framework-73b8966a3c579ab0.js:9:60917)
    at i (framework-73b8966a3c579ab0.js:9:119475)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
    at framework-73b8966a3c579ab0.js:9:98981
a5 @ framework-73b8966a3c579ab0.js:9
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9
uY @ framework-73b8966a3c579ab0.js:9
e @ framework-73b8966a3c579ab0.js:9
(anonymous) @ framework-73b8966a3c579ab0.js:9
oI @ framework-73b8966a3c579ab0.js:9
oS @ framework-73b8966a3c579ab0.js:9
x @ framework-73b8966a3c579ab0.js:33
T @ framework-73b8966a3c579ab0.js:33
main-9ed2a15cbc4c1d51.js:1 Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
    
    at _app-7ecd27c8c48459ad.js:1:26461
    at new en (_app-7ecd27c8c48459ad.js:1:26664)
    at _app-7ecd27c8c48459ad.js:1:43792
    at Object.aM [as useState] (framework-73b8966a3c579ab0.js:9:63832)
    at n.useState (framework-73b8966a3c579ab0.js:25:6154)
    at ev (_app-7ecd27c8c48459ad.js:1:43773)
    at ab (framework-73b8966a3c579ab0.js:9:60917)
    at i (framework-73b8966a3c579ab0.js:9:119475)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
    at framework-73b8966a3c579ab0.js:9:98981
en @ main-9ed2a15cbc4c1d51.js:1
fn @ main-9ed2a15cbc4c1d51.js:1
value @ main-9ed2a15cbc4c1d51.js:1
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9
uY @ framework-73b8966a3c579ab0.js:9
e @ framework-73b8966a3c579ab0.js:9
(anonymous) @ framework-73b8966a3c579ab0.js:9
oI @ framework-73b8966a3c579ab0.js:9
oS @ framework-73b8966a3c579ab0.js:9
x @ framework-73b8966a3c579ab0.js:33
T @ framework-73b8966a3c579ab0.js:33
main-9ed2a15cbc4c1d51.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
en @ main-9ed2a15cbc4c1d51.js:1
fn @ main-9ed2a15cbc4c1d51.js:1
value @ main-9ed2a15cbc4c1d51.js:1
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9
uY @ framework-73b8966a3c579ab0.js:9
e @ framework-73b8966a3c579ab0.js:9
(anonymous) @ framework-73b8966a3c579ab0.js:9
oI @ framework-73b8966a3c579ab0.js:9
oS @ framework-73b8966a3c579ab0.js:9
x @ framework-73b8966a3c579ab0.js:33
T @ framework-73b8966a3c579ab0.js:33

**Comment by shobrook** [comment]
This was a result of not having the right environment variables set when trying to run this locally. No longer a relevant issue.
