### ISSUE TITLE
Support for Lua

### ISSUE THREAD

**Issue by nathangur** [shobrook/adrenaline#57]
Lua is pretty widely used and support for it would be greatly appreciated!!!

**Comment by ItsAnye** [comment]
It's not pretty widely used lmao - 95% of it's usage is through Roblox

**Comment by GGProGaming** [comment]
No I wouldn't say so. It's often used with the C libraries or as a modding language for many games like Factorio and Teardown

**Comment by shobrook** [comment]
Support added!
