### ISSUE TITLE
Very cool project! But seems to get fixated on certain code features

### ISSUE THREAD

**Issue by dandv** [shobrook/adrenaline#58]
Repro steps:
1. Add repo weaviate/weaviate
2. Ask, How does the commenting widget work? [great answer]
3. Tell me about the first code snippet
 > There are three code snippets here, but none of them specifically relate to a commenting widget. The first code snippet is a contact form that sends an email, the second code snippet is a component that uses Giscus to add comments to a blog post or documentation page, and the third code snippet is a newsletter subscription form. Can you provide more context or information about the commenting widget you're referring to?
4. The second one is in fact the commenting widget [good answer]
5. Locate the first code snippet, the contact form
> Based on the code snippets provided, there are a few different commenting widgets being used. 

> The first code snippet shows a form for users to submit their contact information, and the form data is sent to a server using an XMLHttpRequest. However, there is no commenting widget being used in this code snippet. 

> The second code snippet shows two components, `GiscusDocComment` and `GiscusBlogPostComment`, that use the `@giscus/react` package to embed a commenting widget into the Weaviate website. The `GiscusParams` object contains configuration options for the commenting widget, such as the repository and category to associate the comments with, and the `Giscus` component renders the widget with the appropriate configuration options based on whether it is being used on a documentation page or a blog post. 

> The third code snippet shows a newsletter subscription form, which also does not use a commenting widget.

So from step 3 onward, it got fixated on the Giscus commenting widget.

**Comment by shobrook** [comment]
Curious –– how is this performing now? We've made dramatic updates since this was posted.
