### ISSUE TITLE
Fail start-local

### ISSUE THREAD

**Issue by seyeong-han** [shobrook/adrenaline#8]
Firstly, I really appreciate with your effort to offer this great tool.

While running `npm run start-local`, I got this error as following.
Could you please check this error?
Thanks!
```
> adrenaline@0.1.0 start-local /home/han/project/adrenaline
> react-scripts start

/home/han/project/adrenaline/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/han/project/adrenaline/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adrenaline@0.1.0 start-local: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adrenaline@0.1.0 start-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/han/.npm/_logs/2023-01-16T00_09_03_066Z-debug.log
```

**Comment by mdabir1203** [comment]
I am also facing the same issue

<img width="677" alt="image" src="https://user-images.githubusercontent.com/66947064/213054467-c05af2e4-459a-4d9e-a88d-3570c310b0cf.png">

**Comment by jmburgues** [comment]
Same here, on Windows 11. Full log file:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'start-local' ]
> 2 info using npm@6.9.0
> 3 info using node@v10.16.3
> 4 verbose run-script [ 'prestart-local', 'start-local', 'poststart-local' ]
> 5 info lifecycle adrenaline@0.1.0~prestart-local: adrenaline@0.1.0
> 6 info lifecycle adrenaline@0.1.0~start-local: adrenaline@0.1.0
> 7 verbose lifecycle adrenaline@0.1.0~start-local: unsafe-perm in lifecycle true
> 8 verbose lifecycle adrenaline@0.1.0~start-local: PATH: C:\Users\secur\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\secur\repos\adrenaline\adrenaline\node_modules\.bin;C:\Users\secur\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\secur\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Eclipse Adoptium\jdk-8.0.345.1-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\secur\.jdks\corretto-1.8.0_342\bin;C:\Gradle\bin;C:\Users\secur\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Amazon\AWSCLIV2;C:\Program Files\Git\cmd;C:\Users\secur\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.1\bin;C:\Users\secur\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\secur\apache-maven-3.8.6\bin;C:\Users\secur\PycharmProjects\re-evaluateClaims\venv\Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
> 9 verbose lifecycle adrenaline@0.1.0~start-local: CWD: C:\Users\secur\repos\adrenaline\adrenaline
> 10 silly lifecycle adrenaline@0.1.0~start-local: Args: [ '/d /s /c', 'react-scripts start' ]
> 11 silly lifecycle adrenaline@0.1.0~start-local: Returned: code: 1  signal: null
> 12 info lifecycle adrenaline@0.1.0~start-local: Failed to exec start-local script
> 13 verbose stack Error: adrenaline@0.1.0 start-local: `react-scripts start`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\secur\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
> 13 verbose stack     at EventEmitter.emit (events.js:198:13)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\secur\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:198:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid adrenaline@0.1.0
> 15 verbose cwd C:\Users\secur\repos\adrenaline\adrenaline
> 16 verbose Windows_NT 10.0.22621
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-local"
> 18 verbose node v10.16.3
> 19 verbose npm  v6.9.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error adrenaline@0.1.0 start-local: `react-scripts start`
> 22 error Exit status 1
> 23 error Failed at the adrenaline@0.1.0 start-local script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by shobrook** [comment]
I'm unable to reproduce this.
