### ISSUE TITLE
website isnt working

### ISSUE THREAD

**Issue by KauaBR0** [shobrook/adrenaline#97]
![image](https://github.com/shobrook/adrenaline/assets/88597158/ffb6254e-71b0-42b0-a102-4f9e571250b3)

**Comment by shobrook** [comment]
Can you share the console logs please? Unable to reproduce this.

**Comment by KauaBR0** [comment]
> Can you share the console logs please? Unable to reproduce this.

![image](https://github.com/shobrook/adrenaline/assets/88597158/ac192a9c-be92-43e0-bc0f-fa13f788bab4)
![image](https://github.com/shobrook/adrenaline/assets/88597158/62297094-068d-4a3a-87f6-ce7069103a03)

in the console doesnt appear nothing, but the network appears as pending and 200, but it takes a little while

**Comment by shobrook** [comment]
I've confirmed that it's working on multiple browsers, on multiple different internet connections.

My guess is it's either an internet connectivity issue or possibly an ad blocker? To confirm this, try visiting the site on your phone or a device that isn't connected to WiFi.

**Comment by KauaBR0** [comment]
i try it, disable the adblock and isnt works, try from my mobile too. Maybe an internet issue. It's been like this since yesterday

**Comment by shobrook** [comment]
And other websites are working just fine?

**Comment by KauaBR0** [comment]
> And other websites are working just fine?

Yes, my internet is working ok

**Comment by KauaBR0** [comment]
today its a little bit bad, but yesterday is okay and the AI keep dont opening

**Comment by KauaBR0** [comment]
hey, it's working for me again

**Comment by shobrook** [comment]
Glad it's working now! We didn't change anything, and looking at our logs there wasn't any recorded downtime. My guess is it was an issue with your network but please let me know if it happens again.
