### ISSUE TITLE
Doesnt allow you try it just shows popup over an over when you try

### ISSUE THREAD

**Issue by liveaffiliates** [shobrook/adrenaline#99]
1) If you can, please include a screenshot of your problem
2) Please include the name of your operating system
3) If you can, steps to reproduce are super helpful

this doesnt work to try it out no way I would pay if it says you can try it but all it does it show the upgrade over and over. Not sure if this is a bug or expected behaviour.

Thanks

**Comment by shobrook** [comment]
Hi, this was a bug and it should be fixed now. Please let me know if you're still running into it!
